build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.8

install:
  - activate test-environment
  - pip install .
  - pip install -r requirements.txt

test_script:
  - nosetests -v piedomains/tests
#---------------------------------#
