build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.8

- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2018
    PYTHON: "C:\\Miniconda37-x64"
    PYTHON_VERSION: "3.8"
    PYTHON_ARCH: "64"
    PCL_ROOT: "C:\\Program Files\\PCL 1.9.1"
    PCL_VERSION: "1.9"
    OPENNI_VERSION: "2.2"
    OPENNI_ROOT: "C:\\Program Files\\OpenNI2\\Redist\\"
    APPVEYOR_OPENNI_ROOT: ".\\AppVeyor\\OpenNI2\\x64\\Redist"
    NOSEATTR: "not pcl_ver_0_4"

install:
  - pip install .
  - pip install -r requirements.txt

test_script:
  - nosetests -v piedomains/tests
#---------------------------------#
