name: Windows
permissions:
  contents: read
on: [push, pull_request]

jobs:
  tests:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

# no binary package for lxml for 3.11 yet
#        - python-version: "3.11"
#          env:
#            TOXENV: py
#        - python-version: "3.11"
#          env:
#            TOXENV: asyncio

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tests (excluding ML tests due to TensorFlow DLL issues on Windows)
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pytest piedomains/tests -v -m "not ml"
