name: Ubuntu
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system libraries
      if: matrix.python-version == 'pypy3.11' || contains(matrix.env.TOXENV, 'pinned')
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-dev libxslt-dev
    - name: Run tests
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pytest piedomains/tests -v
    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
