name: macOS
on: [push, pull_request]

jobs:
  tests:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pytest piedomains/tests -v -m "not ml"
    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
